// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	BADREQUEST    ErrorCode = "BAD_REQUEST"
	CONFLICT      ErrorCode = "CONFLICT"
	INTERNALERROR ErrorCode = "INTERNAL_ERROR"
	NOTFOUND      ErrorCode = "NOT_FOUND"
	RATELIMITED   ErrorCode = "RATE_LIMITED"
	UNAUTHORIZED  ErrorCode = "UNAUTHORIZED"
)

// Defines values for ItemType.
const (
	File   ItemType = "file"
	Folder ItemType = "folder"
)

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// Defines values for SyncMode.
const (
	Auto        SyncMode = "auto"
	Full        SyncMode = "full"
	Incremental SyncMode = "incremental"
)

// Defines values for SyncStatus.
const (
	Cancelled   SyncStatus = "cancelled"
	Done        SyncStatus = "done"
	Error       SyncStatus = "error"
	Idle        SyncStatus = "idle"
	Interrupted SyncStatus = "interrupted"
	Running     SyncStatus = "running"
)

// CrawlStats defines model for CrawlStats.
type CrawlStats struct {
	// EndedAt Unix timestamp.
	EndedAt         int `json:"endedAt"`
	FailedRequests  int `json:"failedRequests"`
	FilesDiscovered int `json:"filesDiscovered"`
	FilesIndexed    int `json:"filesIndexed"`
	FoldersVisited  int `json:"foldersVisited"`
	PagesFetched    int `json:"pagesFetched"`
	SkippedFiles    int `json:"skippedFiles"`

	// StartedAt Unix timestamp.
	StartedAt int `json:"startedAt"`
}

// DownloadURLResponse defines model for DownloadURLResponse.
type DownloadURLResponse struct {
	DownloadUrl string `json:"download_url"`
	FileId      int    `json:"file_id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      ErrorCode `json:"code"`
	Message   string    `json:"message"`
	RequestId *string   `json:"request_id,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	RunningSync bool   `json:"running_sync"`
	Status      string `json:"status"`
}

// IncrementalSyncStats defines model for IncrementalSyncStats.
type IncrementalSyncStats struct {
	ChangesFetched int `json:"changesFetched"`
	CursorAfter    int `json:"cursorAfter"`
	CursorBefore   int `json:"cursorBefore"`
	Deleted        int `json:"deleted"`
	SkippedDeletes int `json:"skippedDeletes"`
	SkippedUpserts int `json:"skippedUpserts"`
	Upserted       int `json:"upserted"`
}

// IndexDocument defines model for IndexDocument.
type IndexDocument struct {
	// CreatedAt Unix timestamp.
	CreatedAt       int     `json:"created_at"`
	DocId           string  `json:"doc_id"`
	HighlightedName *string `json:"highlighted_name,omitempty"`
	InTrash         bool    `json:"in_trash"`
	IsDeleted       bool    `json:"is_deleted"`

	// ModifiedAt Unix timestamp.
	ModifiedAt int      `json:"modified_at"`
	Name       string   `json:"name"`
	ParentId   int      `json:"parent_id"`
	PathText   string   `json:"path_text"`
	Sha1       string   `json:"sha1"`
	Size       int      `json:"size"`
	SourceId   int      `json:"source_id"`
	Type       ItemType `json:"type"`
}

// ItemType defines model for ItemType.
type ItemType string

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Items []IndexDocument `json:"items"`
	Total int             `json:"total"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Meili Present only when status is not_ready.
	Meili  *string             `json:"meili,omitempty"`
	Status ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// RemoteSearchItem defines model for RemoteSearchItem.
type RemoteSearchItem struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// RemoteSearchResponse defines model for RemoteSearchResponse.
type RemoteSearchResponse struct {
	Files        []RemoteSearchItem `json:"files"`
	Folders      []RemoteSearchItem `json:"folders"`
	PageCapacity int                `json:"page_capacity"`
	PageCount    int                `json:"page_count"`
	PageId       int                `json:"page_id"`
	TotalCount   int                `json:"total_count"`
}

// RootSyncProgress defines model for RootSyncProgress.
type RootSyncProgress struct {
	EstimatedTotalDocs *int       `json:"estimatedTotalDocs"`
	RootFolderId       int        `json:"rootFolderId"`
	Stats              CrawlStats `json:"stats"`
	Status             string     `json:"status"`

	// UpdatedAt Unix timestamp.
	UpdatedAt int `json:"updatedAt"`
}

// SyncMode defines model for SyncMode.
type SyncMode string

// SyncProgressState defines model for SyncProgressState.
type SyncProgressState struct {
	ActiveRoot       *int                  `json:"activeRoot"`
	AggregateStats   CrawlStats            `json:"aggregateStats"`
	CompletedRoots   []int                 `json:"completedRoots"`
	IncrementalStats *IncrementalSyncStats `json:"incrementalStats"`
	LastError        *string               `json:"lastError,omitempty"`
	Mode             *SyncMode             `json:"mode,omitempty"`

	// RootNames Map of root folder ID to name.
	RootNames *map[string]string `json:"rootNames,omitempty"`

	// RootProgress Map of root folder ID (as string key) to its progress.
	RootProgress map[string]RootSyncProgress `json:"rootProgress"`
	Roots        []int                       `json:"roots"`

	// StartedAt Unix timestamp.
	StartedAt int        `json:"startedAt"`
	Status    SyncStatus `json:"status"`

	// UpdatedAt Unix timestamp.
	UpdatedAt    int               `json:"updatedAt"`
	Verification *SyncVerification `json:"verification"`
}

// SyncStartRequest defines model for SyncStartRequest.
type SyncStartRequest struct {
	CheckpointTemplate *string   `json:"checkpoint_template,omitempty"`
	DepartmentIds      *[]int    `json:"department_ids,omitempty"`
	IncludeDepartments *bool     `json:"include_departments"`
	IncrementalQuery   *string   `json:"incremental_query,omitempty"`
	Mode               *SyncMode `json:"mode,omitempty"`
	ProgressEvery      *int      `json:"progress_every,omitempty"`
	ResumeProgress     *bool     `json:"resume_progress"`
	RootFolderIds      *[]int    `json:"root_folder_ids,omitempty"`
	RootWorkers        *int      `json:"root_workers,omitempty"`
	WindowOverlapMs    *int      `json:"window_overlap_ms,omitempty"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus string

// SyncVerification defines model for SyncVerification.
type SyncVerification struct {
	CrawledDocCount    int       `json:"crawledDocCount"`
	DiscoveredDocCount int       `json:"discoveredDocCount"`
	MeiliDocCount      int       `json:"meiliDocCount"`
	SkippedCount       int       `json:"skippedCount"`
	Verified           bool      `json:"verified"`
	Warnings           *[]string `json:"warnings,omitempty"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	OauthHost    *string `json:"oauth_host,omitempty"`
	SubId        *int    `json:"sub_id,omitempty"`
	SubType      *string `json:"sub_type,omitempty"`

	// Token Existing bearer token (if available).
	Token *string `json:"token,omitempty"`
}

// FileIdParam defines model for FileIdParam.
type FileIdParam = int

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// QueryParam defines model for QueryParam.
type QueryParam = string

// ValidPeriodParam defines model for ValidPeriodParam.
type ValidPeriodParam = int

// AppDownloadURLParams defines parameters for AppDownloadURL.
type AppDownloadURLParams struct {
	// FileId Numeric file ID.
	FileId FileIdParam `form:"file_id" json:"file_id"`

	// ValidPeriod Download URL validity period in seconds.
	ValidPeriod *ValidPeriodParam `form:"valid_period,omitempty" json:"valid_period,omitempty"`
}

// AppSearchParams defines parameters for AppSearch.
type AppSearchParams struct {
	// Query Search query string (alias `q` also accepted).
	Query    QueryParam `form:"query" json:"query"`
	Page     *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int       `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// DownloadURLParams defines parameters for DownloadURL.
type DownloadURLParams struct {
	// FileId Numeric file ID.
	FileId FileIdParam `form:"file_id" json:"file_id"`

	// ValidPeriod Download URL validity period in seconds.
	ValidPeriod *ValidPeriodParam `form:"valid_period,omitempty" json:"valid_period,omitempty"`
}

// LocalSearchParams defines parameters for LocalSearch.
type LocalSearchParams struct {
	// Query Search query string (alias `q` also accepted).
	Query QueryParam `form:"query" json:"query"`

	// Page Page number (1-based).
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of results per page.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Type Item type filter.
	Type     *string `form:"type,omitempty" json:"type,omitempty"`
	ParentId *int    `form:"parent_id,omitempty" json:"parent_id,omitempty"`

	// UpdatedAfter Unix timestamp lower bound.
	UpdatedAfter *int `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// UpdatedBefore Unix timestamp upper bound.
	UpdatedBefore *int `form:"updated_before,omitempty" json:"updated_before,omitempty"`

	// IncludeDeleted Include soft-deleted documents.
	IncludeDeleted *bool `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// RemoteSearchParams defines parameters for RemoteSearch.
type RemoteSearchParams struct {
	// Query Search query string (alias `q` also accepted).
	Query string `form:"query" json:"query"`

	// Type Item type filter.
	Type             *string `form:"type,omitempty" json:"type,omitempty"`
	PageId           *int    `form:"page_id,omitempty" json:"page_id,omitempty"`
	QueryFilter      *string `form:"query_filter,omitempty" json:"query_filter,omitempty"`
	SearchInFolder   *int    `form:"search_in_folder,omitempty" json:"search_in_folder,omitempty"`
	UpdatedTimeRange *string `form:"updated_time_range,omitempty" json:"updated_time_range,omitempty"`
}

// StartSyncJSONRequestBody defines body for StartSync for application/json ContentType.
type StartSyncJSONRequestBody = SyncStartRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = TokenRequest
