// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	BADREQUEST    ErrorCode = "BAD_REQUEST"
	CONFLICT      ErrorCode = "CONFLICT"
	INTERNALERROR ErrorCode = "INTERNAL_ERROR"
	NOTFOUND      ErrorCode = "NOT_FOUND"
	RATELIMITED   ErrorCode = "RATE_LIMITED"
	UNAUTHORIZED  ErrorCode = "UNAUTHORIZED"
)

// Defines values for ItemType.
const (
	File   ItemType = "file"
	Folder ItemType = "folder"
)

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// DownloadURLResponse defines model for DownloadURLResponse.
type DownloadURLResponse struct {
	DownloadUrl string `json:"download_url"`
	FileId      int    `json:"file_id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      ErrorCode `json:"code"`
	Message   string    `json:"message"`
	RequestId *string   `json:"request_id,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	RunningSync bool   `json:"running_sync"`
	Status      string `json:"status"`
}

// IndexDocument defines model for IndexDocument.
type IndexDocument struct {
	// CreatedAt Unix timestamp.
	CreatedAt       int     `json:"created_at"`
	DocId           string  `json:"doc_id"`
	HighlightedName *string `json:"highlighted_name,omitempty"`
	InTrash         bool    `json:"in_trash"`
	IsDeleted       bool    `json:"is_deleted"`

	// ModifiedAt Unix timestamp.
	ModifiedAt int      `json:"modified_at"`
	Name       string   `json:"name"`
	ParentId   int      `json:"parent_id"`
	PathText   string   `json:"path_text"`
	Sha1       string   `json:"sha1"`
	Size       int      `json:"size"`
	SourceId   int      `json:"source_id"`
	Type       ItemType `json:"type"`
}

// ItemType defines model for ItemType.
type ItemType string

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Items []IndexDocument `json:"items"`
	Total int             `json:"total"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Meili Present only when status is not_ready.
	Meili  *string             `json:"meili,omitempty"`
	Status ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// RemoteSearchItem defines model for RemoteSearchItem.
type RemoteSearchItem struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// RemoteSearchResponse defines model for RemoteSearchResponse.
type RemoteSearchResponse struct {
	Files        []RemoteSearchItem `json:"files"`
	Folders      []RemoteSearchItem `json:"folders"`
	PageCapacity int                `json:"page_capacity"`
	PageCount    int                `json:"page_count"`
	PageId       int                `json:"page_id"`
	TotalCount   int                `json:"total_count"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	OauthHost    *string `json:"oauth_host,omitempty"`
	SubId        *int    `json:"sub_id,omitempty"`
	SubType      *string `json:"sub_type,omitempty"`

	// Token Existing bearer token (if available).
	Token *string `json:"token,omitempty"`
}

// FileIdParam defines model for FileIdParam.
type FileIdParam = int

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// QueryParam defines model for QueryParam.
type QueryParam = string

// ValidPeriodParam defines model for ValidPeriodParam.
type ValidPeriodParam = int

// AppDownloadURLParams defines parameters for AppDownloadURL.
type AppDownloadURLParams struct {
	// FileId Numeric file ID.
	FileId FileIdParam `form:"file_id" json:"file_id"`

	// ValidPeriod Download URL validity period in seconds.
	ValidPeriod *ValidPeriodParam `form:"valid_period,omitempty" json:"valid_period,omitempty"`
}

// AppSearchParams defines parameters for AppSearch.
type AppSearchParams struct {
	// Query Search query string (alias `q` also accepted).
	Query    QueryParam `form:"query" json:"query"`
	Page     *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int       `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// DownloadURLParams defines parameters for DownloadURL.
type DownloadURLParams struct {
	// FileId Numeric file ID.
	FileId FileIdParam `form:"file_id" json:"file_id"`

	// ValidPeriod Download URL validity period in seconds.
	ValidPeriod *ValidPeriodParam `form:"valid_period,omitempty" json:"valid_period,omitempty"`
}

// LocalSearchParams defines parameters for LocalSearch.
type LocalSearchParams struct {
	// Query Search query string (alias `q` also accepted).
	Query QueryParam `form:"query" json:"query"`

	// Page Page number (1-based).
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of results per page.
	PageSize *PageSizeParam `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Type Item type filter.
	Type     *string `form:"type,omitempty" json:"type,omitempty"`
	ParentId *int    `form:"parent_id,omitempty" json:"parent_id,omitempty"`

	// UpdatedAfter Unix timestamp lower bound.
	UpdatedAfter *int `form:"updated_after,omitempty" json:"updated_after,omitempty"`

	// UpdatedBefore Unix timestamp upper bound.
	UpdatedBefore *int `form:"updated_before,omitempty" json:"updated_before,omitempty"`

	// IncludeDeleted Include soft-deleted documents.
	IncludeDeleted *bool `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// RemoteSearchParams defines parameters for RemoteSearch.
type RemoteSearchParams struct {
	// Query Search query string (alias `q` also accepted).
	Query string `form:"query" json:"query"`

	// Type Item type filter.
	Type             *string `form:"type,omitempty" json:"type,omitempty"`
	PageId           *int    `form:"page_id,omitempty" json:"page_id,omitempty"`
	QueryFilter      *string `form:"query_filter,omitempty" json:"query_filter,omitempty"`
	SearchInFolder   *int    `form:"search_in_folder,omitempty" json:"search_in_folder,omitempty"`
	UpdatedTimeRange *string `form:"updated_time_range,omitempty" json:"updated_time_range,omitempty"`
}

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = TokenRequest
